# Generated by Django 2.0.2 on 2018-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180417_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.CharField(default='', max_length=15),
        ),
    ]
