# Generated by Django 2.0.2 on 2018-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fooditem_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
