# Generated by Django 2.0.2 on 2018-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180417_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='dhall',
            field=models.CharField(default='', max_length=100),
        ),
    ]
