# Generated by Django 2.0.2 on 2018-05-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_fooditem_dhall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
