# Generated by Django 2.0.2 on 2018-05-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20180508_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='allergens',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.CharField(default='', max_length=500),
        ),
    ]
