# Generated by Django 2.0.2 on 2018-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20180509_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='allergens',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
