# Generated by Django 2.0.2 on 2018-05-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
