# Generated by Django 2.0.2 on 2018-05-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180510_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='favorites',
            field=models.TextField(default=''),
        ),
    ]
